### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by dewittpe** [kevjosey/cbal#2]
There are at least three issues to address in the documentation.  From R CMD check (assuming #1 has been accepted)

```
* checking R code for possible problems ... NOTE
transport: no visible binding for global variable ‘Y1’
Undefined global functions or variables:
  Y1
* checking Rd files ... NOTE
prepare_Rd: lagrange.Rd:36-38: Dropping empty section \references
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'balance'
  ‘Y’
```

At `Y1` in `transport` needs to be defined.  It is used https://github.com/kevjosey/cbal/blob/62366a8bc2e82f0d093d7f509f9bf1dc257ecc59/R/transport.R#L44
but is not in the function arguments or `@param` tags.  The tests are passing because the `...` is capturing the `Y1` input.  However, adding Y1 to the functional arguments will result in the tests failing.  

I have not check for a solution for the undocumented argument in `balance`.

@kevjosey please update the documentation so the notes and warning are resolved.

**Comment by kjosey** [comment]
Hey @dewittpe, 

You are correct that this was left out. However, transport() should not depend on Y or Y1, so I removed it from the function. It should not have been there in the first place.
